import type { KanbanColumn } from '../shared/types'

/**
 * Builds the file that tells a coding agent how to use the board.
 *
 * It is generated rather than written by hand so that the column names and the
 * folder path always match what the extension is actually configured to do. A
 * hand written copy would go stale the first time either changed.
 */

/** Lets us tell our own file apart from one somebody has since edited. */
export const GENERATED_MARKER = '<!-- generated by kanbanmd -->'

export function buildAgentInstructions(
  columns: KanbanColumn[],
  featuresDirectory: string
): string {
  const statuses = columns.map(c => c.id)
  const doneId = statuses.includes('done') ? 'done' : statuses[statuses.length - 1]
  const firstId = statuses[0] ?? 'backlog'

  const columnTable = columns
    .map(c => `| \`${c.id}\` | ${c.name} |`)
    .join('\n')

  return `${GENERATED_MARKER}

# How to use this board

This folder is a kanban board. Every card is one markdown file, so you can read
the board and change it with ordinary file edits. The extension watches this
folder and redraws itself when a file changes, so there is nothing to call and
nothing to restart.

Do not edit this file. It is regenerated from the extension's settings.

## Where the cards are

Cards live in \`${featuresDirectory}/\`. Finished cards live in
\`${featuresDirectory}/${doneId}/\`. Everything else sits in the top folder,
whatever column it is in.

## What a card looks like

\`\`\`markdown
---
id: "add-rate-limiting-2026-07-28"
status: "${firstId}"
priority: "medium"
assignee: null
epic: null
dueDate: null
created: "2026-07-28T09:00:00.000Z"
modified: "2026-07-28T09:00:00.000Z"
completedAt: null
labels: ["api", "backend"]
order: "a0"
---

# Add rate limiting to the public API

Anyone can hammer the endpoint today. Add a per key limit and return 429 once
it is passed.
\`\`\`

The first \`#\` heading is the card title shown on the board. Everything under
it is the body, and the first few lines of it show on the card as well.

## The fields

| Field | What goes in it |
| --- | --- |
| \`id\` | Unique, and matches the file name without \`.md\`. |
| \`status\` | One of the column ids below. |
| \`priority\` | \`critical\`, \`high\`, \`medium\` or \`low\`. |
| \`assignee\` | A name in quotes, or \`null\`. |
| \`epic\` | A group name in quotes, or \`null\`. |
| \`dueDate\` | An ISO date in quotes, or \`null\`. |
| \`created\` | ISO timestamp, set once. |
| \`modified\` | ISO timestamp, update it when you change the card. |
| \`completedAt\` | ISO timestamp when it reached ${doneId}, otherwise \`null\`. |
| \`labels\` | A list of strings, possibly empty. |
| \`order\` | Sort key within the column. Short strings sort as text, so \`a0\`, \`a1\`, \`a2\`. |

Every field has to be present. Use \`null\` rather than leaving one out.

## The columns

| Status | Shown as |
| --- | --- |
${columnTable}

## Doing things

**Add a card.** Write a new file in \`${featuresDirectory}/\` with all the
fields above. Name it after the title, in lower case with dashes, and add the
date, for example \`add-rate-limiting-2026-07-28.md\`.

**Move a card.** Change \`status\` to another column id and update \`modified\`.
If you move it to \`${doneId}\`, also set \`completedAt\` and move the file into
the \`${doneId}/\` folder.

**Work through the board.** Read the cards, pick one, do the work, then move it
and write what you did into the body of the card. The body is the right place
for notes, decisions and anything the next person needs.

**Leave a trail.** Someone reads these later to find out what happened, so
write the body for them rather than as a status line.
`
}
